name: ip testing thing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  test:
    concurrency:
      group: ip-status
      cancel-in-progress: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: sync branch
        run: |
          git pull --rebase origin main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: run web check
        run: python check.py

      - name: commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md
          git diff --cached --quiet && exit 0

          git commit -m "update status"
          git push
